[54.023742676] 2018-05-14 23:03:04,420 - INFO - launcher: Starting sanity checks
[55.023670197] 2018-05-14 23:03:04,421 - INFO - launcher: Checking for Python 3.5+
[55.023670197] 2018-05-14 23:03:04,421 - INFO - launcher: Checking console encoding
[56.028127670] 2018-05-14 23:03:04,422 - INFO - launcher: Setting console encoding to UTF-8
[56.028127670] 2018-05-14 23:03:04,422 - INFO - launcher: Ensuring we're in the right environment
[58.023452759] 2018-05-14 23:03:04,424 - INFO - launcher: Adding local bins/ folder to path
[60.024499893] 2018-05-14 23:03:04,426 - INFO - launcher: Required checks passed.
[61.023473740] 2018-05-14 23:03:04,427 - INFO - launcher: Optional checks passed.
[62.023878098] 2018-05-14 23:03:04,428 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.9715247154235840] 2018-05-14 23:03:06,338 - WARNING - musicbot.config | In config.py::MainThread(1596), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[1.9725244045257568] 2018-05-14 23:03:06,339 - INFO - musicbot.config | In config.py::MainThread(1596), line 123 in run_checks: Using i18n: config/i18n/en.json
[1.9765238761901855] 2018-05-14 23:03:06,343 - DEBUG - musicbot.json | In json.py::MainThread(1596), line 8 in __init__: Init JSON obj with config/i18n/en.json
[2.4696562290191650] 2018-05-14 23:03:06,836 - DEBUG - musicbot.bot | In bot.py::MainThread(1596), line 227 in _setup_logging: Set logging level to INFO
[2.4696562290191650] 2018-05-14 23:03:06,836 - INFO - musicbot.bot | In bot.py::MainThread(1596), line 84 in __init__: Starting MusicBot 1.9.7
[2.4706549644470215] 2018-05-14 23:03:06,837 - WARNING - musicbot.bot | In bot.py::MainThread(1596), line 87 in __init__: Autoplaylist is empty, disabling.
[7.8990037441253662] 2018-05-14 23:03:12,265 - DEBUG - musicbot.bot | In bot.py::MainThread(1596), line 1074 in on_ready: Connection established, ready to go.
[7.9000091552734375] 2018-05-14 23:03:12,266 - DEBUG - musicbot.bot | In bot.py::MainThread(1596), line 339 in _cache_app_info: Caching app info
[8.0660581588745117] 2018-05-14 23:03:12,432 - DEBUG - musicbot.bot | In bot.py::MainThread(1596), line 889 in _scheck_ensure_env: Ensuring data folders exist
[8.0860576629638672] 2018-05-14 23:03:12,452 - DEBUG - musicbot.bot | In bot.py::MainThread(1596), line 905 in _scheck_server_permissions: Checking server permissions
[8.0860576629638672] 2018-05-14 23:03:12,452 - DEBUG - musicbot.bot | In bot.py::MainThread(1596), line 909 in _scheck_autoplaylist: Auditing autoplaylist
[8.0860576629638672] 2018-05-14 23:03:12,452 - DEBUG - musicbot.bot | In bot.py::MainThread(1596), line 913 in _scheck_configs: Validating config
[8.0860576629638672] 2018-05-14 23:03:12,452 - DEBUG - musicbot.config | In config.py::MainThread(1596), line 212 in async_validate: Validating options...
[8.0860576629638672] 2018-05-14 23:03:12,452 - DEBUG - musicbot.bot | In bot.py::MainThread(1596), line 916 in _scheck_configs: Validating permissions config
[8.0860576629638672] 2018-05-14 23:03:12,452 - DEBUG - musicbot.permissions | In permissions.py::MainThread(1596), line 64 in async_validate: Validating permissions...
[8.0870602130889893] 2018-05-14 23:03:12,453 - INFO - musicbot.bot | In bot.py::MainThread(1596), line 1091 in on_ready: Connected: 437706523582398464/Hector's Bot#7939
[8.0880603790283203] 2018-05-14 23:03:12,454 - INFO - musicbot.bot | In bot.py::MainThread(1596), line 1099 in on_ready: Owner:     344436733846355978/Hector#7715

[8.0890634059906006] 2018-05-14 23:03:12,455 - INFO - musicbot.bot | In bot.py::MainThread(1596), line 1102 in on_ready: Server List:
[8.0900590419769287] 2018-05-14 23:03:12,456 - INFO - musicbot.bot | In bot.py::MainThread(1596), line 1105 in on_ready:  - Force&Savke Army
[8.0910601615905762] 2018-05-14 23:03:12,457 - INFO - musicbot.bot | In bot.py::MainThread(1596), line 1105 in on_ready:  - Develop Testing Server
[8.0910601615905762] 2018-05-14 23:03:12,457 - INFO - musicbot.bot | In bot.py::MainThread(1596), line 1151 in on_ready: Not bound to any text channels
[8.0920608043670654] 2018-05-14 23:03:12,458 - INFO - musicbot.bot | In bot.py::MainThread(1596), line 1177 in on_ready: Not autojoining any voice channels
[59.7499930858612061] 2018-05-14 23:04:04,116 - INFO - musicbot.bot | In bot.py::MainThread(1596), line 2734 in on_message: 344436733846355978/Hector#7715: !summon
[59.7509880065917969] 2018-05-14 23:04:04,117 - ERROR - musicbot.bot | In bot.py::MainThread(1596), line 2863 in on_message: Error in summon: CommandError: You are not in a voice channel!
Traceback (most recent call last):
  File "C:\Users\Hector\MusicBot\musicbot\bot.py", line 2841, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\Hector\MusicBot\musicbot\bot.py", line 1995, in cmd_summon
    raise exceptions.CommandError(self.str.get('cmd-summon-novc', 'You are not in a voice channel!'))
musicbot.exceptions.CommandError: You are not in a voice channel!
[70.9943799972534180] 2018-05-14 23:04:15,360 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(1596), line 2938 in on_voice_state_update: Voice state update for 344436733846355978/Hector#7715 on Develop Testing Server/Music Room -> [CONNECT, MUTE]
